### ISSUE TITLE
Add requests package to Requirements.txt

### ISSUE THREAD

**Issue by eranschweitzer** [pnnl/i2x#11]
It seems like the `requests` package was added as a dependency but is not showing up as a requirement.

I did 
* `pip install -e .` in my local copy of the repo 
* `i2x-der` in the command line

I get the error `ModuleNotFoundError: No module named 'requests'`

**Comment by temcdrm** [comment]
Fixed in https://github.com/pnnl/i2x/commit/29030abf3a3fad75ee06532d09a6b81d783dfd54
