### ISSUE TITLE
Nominal kV = 0 for buses of type bus and source

### ISSUE THREAD

**Issue by eranschweitzer** [pnnl/i2x#12]
The nominal kV data in the NetworkX graph appears to be zero for all buses that do not have specific shunts attached to them.

A consequence of this is that, for example, all 3 phase buses found through `parse_opendss_graph` have zero nominal voltage.

Example code on the 9500 node feeder:
```python
G = i2x.load_builtin_graph('ieee9500')
# loop over nodes and mark zero nominal kv vs non-zero
zerokv = 0
zeroclass = set()
nonzerokv = 0
nonzeroclass = set()
for n, d in G.nodes(data=True):
    if 'ndata' in d:
        if d['ndata']['nomkv'] == 0:
            zerokv += 1
            zeroclass.add(d['nclass'])
        else:
            nonzerokv += 1
            nonzeroclass.add(d['nclass'])

print(f"zerokv = {zerokv}, of class(es): {zeroclass}")
print(f"nonzerokv = {nonzerokv} of class(es) {nonzeroclass}")
```

**Comment by temcdrm** [comment]
Fixed in https://github.com/pnnl/i2x/commit/e036100e08a78276c591d5d163dfdfc386cffe32

The capacitor bus nomkv values were incorrect before at 7.2; they have been corrected to 12.47
