### ISSUE TITLE
Branch Orientation Mismatch

### ISSUE THREAD

**Issue by eranschweitzer** [pnnl/i2x#13]
There appears to be occasional mismatch between the `from`-`to` order of nodes in the graph branches and the `bus1`-`bus2` order.
As an example, branch `ln6413954-1` has is defined by nodes `('m1142851', 'l2955077')` while `bus1='l2955077'` and `bus2='m1142851'`.

In this particular case this is a recloser that gets a monitor attached.
Flipping the from/to definition makes the reading of the monitor make it seem like a purely load pocket is _exporting_ power.

**Comment by temcdrm** [comment]
Addressed in https://github.com/pnnl/i2x/pull/15
