### ISSUE TITLE
Refactoring on develop seems to have caused breaking changes to the GUI

### ISSUE THREAD

**Issue by eranschweitzer** [pnnl/i2x#14]
Some of the api calls have been refactored for the hca functionality and appear to have broken the gui calls.
this is almost certainly due to the ouptus from `run_opendss` where some new outputs were added.
![MicrosoftTeams-image](https://github.com/pnnl/i2x/assets/28018315/cf2bccfd-1e5d-4f88-9b93-e6e12d4d1d52)

**Comment by temcdrm** [comment]
Addressed in https://github.com/pnnl/i2x/pull/15
